export const Types = {
  steel: 'Acier',
  fighting: 'Combat',
  dragon: 'Dragon',
  water: 'Eau',
  electric: 'Electrik',
  fairy: 'Fée',
  fire: 'Feu',
  ice: 'Glace',
  bug: 'Insecte',
  normal: 'Normal',
  grass: 'Plante',
  poison: 'Poison',
  psychic: 'Psy',
  rock: 'Roche',
  ground: 'Sol',
  ghost: 'Spectre',
  dark: 'Ténèbres',
  flying: 'Vol',
};
